version: "3"
services:
  worker:
    build: .
    command: ['bundle', 'exec', 'ruby', 'runner.rb']
    container_name: worker
    depends_on:
    - rabbit
  rabbit:
      image: rabbitmq:3.7.3-management
      container_name: rabbit
      ports:
        - "15672:15672"
      tty: true
      volumes:
        - ./rabbitmq.conf:/etc/rabbitmq.conf:ro
        - ./definitions.json:/etc/rabbitmq/definitions.json:ro
