version: "3"
services:
  rabbit:
      image: rabbitmq:3.7.3-management
      ports:
        - "15672:15672"
        - "5672:5672"
      tty: true
      volumes:
        - ./rabbitmq.conf:/etc/rabbitmq.conf:ro
        - ./definitions.json:/etc/rabbitmq/definitions.json:ro
