version: "3"
services:
  rabbit:
      image: rabbitmq:3-management
      ports:
        - "15672:15672"
        - "5672:5672"
      labels:
        NAME: "rabbit"
      tty: true
      volumes:
        - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
        - ./definitions.json:/etc/rabbitmq/definitions.json:ro
      # command:  bash -c "sleep 10; rabbitmq-server;"
