version: "3"
services:
  rabbitmq-docker:
    image: rabbitmq:3.7.3-management
    container_name: rabbitmq-docker
    ports:
    - "15672:15672"
    volumes:
    - ./configs/rabbitmq.conf:/etc/rabbitmq.conf:ro
    - ./configs/definitions.json:/etc/rabbitmq/definitions.json:ro
