version: "3"
services:
  rabbit:
    image: rabbitmq:3.7.3-management
    container_name: rabbitmq-docker
    ports:
    - "15672:15672"
    volumes:
    - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq.conf:ro
    - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
