version: "3"
services:
  worker:
    build: .
    command: ['ruby', 'lib/runner.rb']
    container_name: worker
    depends_on:
    - rabbit
    environment:
    - RABBITMQ_DEFAULT_URL=amqp://me:me@rabbit/my-vhost
    - RABBITMQ_PREFIX=my
  rabbit:
      image: rabbitmq:3.7.3-management
      container_name: rabbit
      ports:
        - "15672:15672"
      tty: true
      volumes:
        - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq.conf:ro
        - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
